import { test } from 'node:test';
import assert from 'node:assert/strict';
import { parseDiff, placeAnchor, isGenerated, stats, splitDiff } from '../anchors.mjs';

const basic = [
  'diff --git a/src/A.cs b/src/A.cs',
  'index 111..222 100644',
  '--- a/src/A.cs',
  '+++ b/src/A.cs',
  '@@ -10,4 +10,5 @@ class A',
  ' line10',
  '-old11',
  '+new11',
  '+new12',
  ' line13',
  ' line14',
  '',
].join('\n');

test('context and added lines are anchorable on the new side', () => {
  const f = parseDiff(basic).get('src/A.cs');
  assert.deepEqual([...f.newLines].sort((a, b) => a - b), [10, 11, 12, 13, 14]);
  assert.deepEqual([...f.oldLines], [11]);
  assert.equal(f.added, 2);
  assert.equal(f.removed, 1);
});

test('placeAnchor accepts diff lines and rejects lines outside hunks', () => {
  const files = parseDiff(basic);
  assert.deepEqual(placeAnchor(files, { path: 'src/A.cs', line: 12 }), { path: 'src/A.cs', side: 'new', line: 12 });
  assert.deepEqual(placeAnchor(files, { path: 'src/A.cs', line: 11, side: 'old' }), { path: 'src/A.cs', side: 'old', line: 11 });
  assert.equal(placeAnchor(files, { path: 'src/A.cs', line: 40 }), null);
  assert.equal(placeAnchor(files, { path: 'nope.cs', line: 1 }), null);
});

test('paths with spaces survive', () => {
  const d = basic.replaceAll('src/A.cs', 'Advanced Auditing/Db Components/Audit.sql');
  assert.ok(parseDiff(d).has('Advanced Auditing/Db Components/Audit.sql'));
});

test('hunk content that looks like a file header is treated as content', () => {
  const d = [
    'diff --git a/q.sql b/q.sql',
    '--- a/q.sql',
    '+++ b/q.sql',
    '@@ -1,2 +1,2 @@',
    '--- old sql comment',
    '+++i;',
    ' SELECT 1',
    '',
  ].join('\n');
  const f = parseDiff(d).get('q.sql');
  assert.equal(f.path, 'q.sql');
  assert.equal(f.removed, 1);
  assert.equal(f.added, 1);
  assert.deepEqual([...f.newLines].sort(), [1, 2]);
});

test('CRLF diffs parse the same as LF', () => {
  const f = parseDiff(basic.replaceAll('\n', '\r\n')).get('src/A.cs');
  assert.equal(f.added, 2);
  assert.ok(f.newLines.has(14));
});

test('no-newline markers and single-line hunk headers', () => {
  const d = [
    'diff --git a/x.txt b/x.txt',
    '--- a/x.txt',
    '+++ b/x.txt',
    '@@ -5 +5 @@',
    '-a',
    '\\ No newline at end of file',
    '+b',
    '\\ No newline at end of file',
    '',
  ].join('\n');
  const f = parseDiff(d).get('x.txt');
  assert.ok(f.newLines.has(5));
  assert.ok(f.oldLines.has(5));
});

test('deleted files key on the old path and anchor on the old side', () => {
  const d = [
    'diff --git a/gone.cs b/gone.cs',
    'deleted file mode 100644',
    '--- a/gone.cs',
    '+++ /dev/null',
    '@@ -1,2 +0,0 @@',
    '-a',
    '-b',
    '',
  ].join('\n');
  const files = parseDiff(d);
  assert.ok(files.get('gone.cs').deleted);
  assert.deepEqual(placeAnchor(files, { path: 'gone.cs', line: 2, side: 'old' }), { path: 'gone.cs', side: 'old', line: 2 });
});

test('binary files are recorded but never anchorable', () => {
  const d = ['diff --git a/i.png b/i.png', 'Binary files a/i.png and b/i.png differ', ''].join('\n');
  const files = parseDiff(d);
  assert.ok(files.get('i.png').binary);
  assert.equal(placeAnchor(files, { path: 'i.png', line: 1 }), null);
});

test('generated files are detected by name and by header', () => {
  const byName = parseDiff(basic.replaceAll('src/A.cs', 'UI/Form1.Designer.cs')).get('UI/Form1.Designer.cs');
  assert.ok(isGenerated(byName));
  const hdr = basic.replace('+new11', '+// Code generated by NatsCodeGen; DO NOT EDIT');
  assert.ok(isGenerated(parseDiff(hdr).get('src/A.cs')));
  assert.ok(!isGenerated(parseDiff(basic).get('src/A.cs')));
});

test('stats excludes generated files from the changed count', () => {
  const both = basic + basic.replaceAll('src/A.cs', 'package-lock.json');
  const s = stats(parseDiff(both));
  assert.equal(s.changed, 3);
  assert.equal(s.files.length, 2);
});

test('splitDiff groups by directory under the size cap', () => {
  const d = basic + basic.replaceAll('src/A.cs', 'src/B.cs') + basic.replaceAll('src/A.cs', 'lib/C.cs');
  const chunks = splitDiff(parseDiff(d), 6);
  assert.equal(chunks.length, 2);
  assert.deepEqual(chunks.map(c => c.files).flat().sort(), ['lib/C.cs', 'src/A.cs', 'src/B.cs']);
  assert.ok(chunks.every(c => c.text.startsWith('diff --git')));
});

test('C-quoted non-ASCII paths are decoded', () => {
  const d = ['diff --git "a/caf\\303\\251.cs" "b/caf\\303\\251.cs"', '--- "a/caf\\303\\251.cs"', '+++ "b/caf\\303\\251.cs"', '@@ -1 +1 @@', '-a', '+b', ''].join('\n');
  assert.ok(parseDiff(d).has('café.cs'));
});

test('header-only entries keep paths containing " b/"', () => {
  const d = ['diff --git a/dir b/x.bin b/dir b/x.bin', 'Binary files a/dir b/x.bin and b/dir b/x.bin differ', ''].join('\n');
  assert.ok(parseDiff(d).has('dir b/x.bin'));
});
