#!/usr/bin/env node
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const C_ESCAPES = { n: 10, t: 9, r: 13, a: 7, b: 8, f: 12, v: 11, '"': 34, '\\': 92 };

// git C-quotes paths with non-ASCII bytes as octal escapes ("caf\303\251.cs").
function cUnescape(s) {
  const bytes = [];
  for (let i = 0; i < s.length; i++) {
    if (s[i] !== '\\') { bytes.push(...Buffer.from(s[i], 'utf8')); continue; }
    const oct = s.slice(i + 1, i + 4);
    if (/^[0-7]{3}$/.test(oct)) { bytes.push(parseInt(oct, 8)); i += 3; continue; }
    bytes.push(C_ESCAPES[s[i + 1]] ?? s.charCodeAt(i + 1));
    i++;
  }
  return Buffer.from(bytes).toString('utf8');
}

function unquote(p) {
  p = p.replace(/\t.*$/, '');
  if (/^".*"$/.test(p)) p = cUnescape(p.slice(1, -1));
  return p.replace(/^[ab]\//, '');
}

// Header-only entries (binary, pure rename, mode change) have no ---/+++ lines, so the path must
// come from "diff --git a/<p> b/<p>", where <p> itself may contain " b/".
function headerPath(header) {
  const rest = header.slice('diff --git '.length);
  if (rest.startsWith('"')) {
    const i = rest.lastIndexOf(' "b/');
    if (i >= 0) return unquote(rest.slice(i + 1));
  }
  const len = (rest.length - 5) / 2;
  if (Number.isInteger(len) && len > 0 && rest.startsWith('a/') && rest.slice(2 + len, 5 + len) === ' b/'
    && rest.slice(2, 2 + len) === rest.slice(5 + len)) return rest.slice(2, 2 + len);
  const i = rest.lastIndexOf(' b/');
  return i >= 0 ? rest.slice(i + 3) : rest;
}

function newFile(header) {
  const path = headerPath(header);
  return {
    path, oldPath: path, newLines: new Set(), oldLines: new Set(),
    added: 0, removed: 0, binary: false, deleted: false, head: [], raw: [header],
  };
}

export function parseDiff(text) {
  const all = [];
  let cur = null, oldLn = 0, newLn = 0, oldLeft = 0, newLeft = 0;
  for (const line of text.split(/\r?\n/)) {
    // Inside a hunk the remaining-line counters decide what a line is, so content such as
    // a removed SQL comment ("--- x") is never mistaken for a file header.
    if (oldLeft > 0 || newLeft > 0) {
      cur.raw.push(line);
      const c = line[0];
      if (c === '\\') continue;
      if (c === '+') {
        if (cur.head.length < 5) cur.head.push(line.slice(1));
        cur.newLines.add(newLn++); cur.added++; newLeft--;
      } else if (c === '-') {
        cur.oldLines.add(oldLn++); cur.removed++; oldLeft--;
      } else {
        cur.newLines.add(newLn++); oldLn++; newLeft--; oldLeft--;
      }
      continue;
    }
    if (line.startsWith('diff --git ')) { cur = newFile(line); all.push(cur); continue; }
    if (!cur) continue;
    cur.raw.push(line);
    if (line.startsWith('\\')) continue;
    let m;
    if ((m = line.match(/^--- (.*)$/))) {
      if (m[1] !== '/dev/null') cur.oldPath = unquote(m[1]);
    } else if ((m = line.match(/^\+\+\+ (.*)$/))) {
      if (m[1] === '/dev/null') { cur.deleted = true; cur.path = cur.oldPath; }
      else cur.path = unquote(m[1]);
    } else if ((m = line.match(/^@@ -(\d+)(?:,(\d+))? \+(\d+)(?:,(\d+))? @@/))) {
      oldLn = +m[1]; oldLeft = m[2] === undefined ? 1 : +m[2];
      newLn = +m[3]; newLeft = m[4] === undefined ? 1 : +m[4];
    } else if ((m = line.match(/^rename to (.*)$/))) {
      cur.path = unquote(m[1]);
    } else if (line.startsWith('Binary files ')) {
      cur.binary = true;
    }
  }
  return new Map(all.map(f => [f.path, f]));
}

export function placeAnchor(files, { path, line, side = 'new' }) {
  const f = files.get(path);
  if (!f || f.binary) return null;
  const set = side === 'old' ? f.oldLines : f.newLines;
  return set.has(line) ? { path, side, line } : null;
}

const GENERATED_NAME = [
  /\.Designer\.cs$/i, /\.g\.cs$/i, /\.g\.i\.cs$/i, /ModelSnapshot\.cs$/i,
  /(^|\/)package-lock\.json$/, /(^|\/)yarn\.lock$/, /(^|\/)pnpm-lock\.yaml$/, /(^|\/)go\.sum$/,
];
const GENERATED_HEADER = /Code generated .*DO NOT EDIT|<auto-generated|@generated/i;

export const isGenerated = f =>
  GENERATED_NAME.some(re => re.test(f.path)) || f.head.some(l => GENERATED_HEADER.test(l));

export function stats(files) {
  const list = [...files.values()].map(f => ({ path: f.path, added: f.added, removed: f.removed, generated: isGenerated(f) }));
  return { files: list, changed: list.filter(f => !f.generated).reduce((n, f) => n + f.added + f.removed, 0) };
}

export function splitDiff(files, maxChanged) {
  const groups = new Map();
  for (const f of files.values()) {
    if (isGenerated(f)) continue;
    const key = f.path.split('/').slice(0, -1).slice(0, 2).join('/');
    if (!groups.has(key)) groups.set(key, []);
    groups.get(key).push(f);
  }
  const chunks = [];
  let cur = { files: [], changed: 0, parts: [] };
  for (const fs of groups.values()) {
    for (const f of fs) {
      const size = f.added + f.removed;
      if (cur.files.length && cur.changed + size > maxChanged) { chunks.push(cur); cur = { files: [], changed: 0, parts: [] }; }
      cur.files.push(f.path); cur.changed += size; cur.parts.push(f.raw.join('\n'));
    }
  }
  if (cur.files.length) chunks.push(cur);
  return chunks.map(c => ({ files: c.files, changed: c.changed, text: c.parts.join('\n') + '\n' }));
}

function main([cmd, ...a]) {
  const files = a[0] ? parseDiff(readFileSync(a[0], 'utf8')) : null;
  if (cmd === 'stats' && a.length === 1) return stats(files);
  if (cmd === 'place' && a.length === 2)
    return JSON.parse(readFileSync(a[1], 'utf8')).map(f => ({ ...f, anchor: placeAnchor(files, f) }));
  if (cmd === 'split' && a.length === 3) {
    mkdirSync(a[1], { recursive: true });
    return splitDiff(files, Number(a[2])).map((c, i) => {
      const file = join(a[1], `chunk-${i + 1}.diff`);
      writeFileSync(file, c.text);
      return { file, files: c.files, changed: c.changed };
    });
  }
  console.error('usage: anchors.mjs stats <diff> | place <diff> <findings.json> | split <diff> <out-dir> <maxChanged>');
  process.exit(2);
}

const invoked = process.argv[1] && resolve(process.argv[1]).toLowerCase();
if (invoked === fileURLToPath(import.meta.url).toLowerCase())
  console.log(JSON.stringify(main(process.argv.slice(2)), null, 2));
